### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mier68** [ooibc88/FabricSharp#1]
hello，Is there a small example that can be implemented?

**Comment by RUAN0007** [comment]
Hi, Thank you for your interest. For provenance-dependent smart contracts, we give three example contracts described in our paper. You can refer to README in _vldb19_ branch for details.

**Comment by wwqicode** [comment]
Hello, I'm tring to run fabric#, but I don't know how to make peer image. 
I'm using the master branch, and I've got hyperledger/fabric-orderer:forkbase, hyperledger/fabric-ccenv:forkbase and hyperledger/forkbase. I also export DOCKER_DYNAMIC_LINK=true, and tried 'make peer-docker'. But I made image fail, it shows 'cannot find package "ustore" in any of: ...'.
What should I do? What mistakes I have make?
Thank you.
