### ISSUE TITLE
About the maxUniqueKeys in fppscheduler

### ISSUE THREAD

**Issue by workhard-12** [ooibc88/FabricSharp#11]
Hello, I'm trying to read the source code recently. But when I read the fppscheduler/scheduler.go, I was a little confused about the maxUniqueKeys. I think it is set too big, and I don't understand the following lines of code.
`index := key / 64 `
`writeSet[index] |= (uint64(1) << (key % 64))`
`scheduler.txWriteSet[tid] = writeSet`
I think we should convert writeSet[index] to a binary array and assign it to txWriteSet[tid].Could you please tell me what mistakes I have made?
Thank you very much.

**Comment by RUAN0007** [comment]
Hi, thank you for your reach out. Actually, the array _writeset []u64_ is essentially the binary array. In particular, suppose that the _i-th_ bit in _writeset[j]_ is 1, it implies that _tid_ writes up the key with the index _64j+i_. Here, we do not bother to combine the _writeset_ array into a single binary array, as long as all other codes assume this convension of _writeset_ array.

**Comment by workhard-12** [comment]
I think I understand, thank you very much.
