### ISSUE TITLE
About Perfomance

### ISSUE THREAD

**Issue by Sybilzz** [ooibc88/FabricSharp#12]
Hello, I have reproduced the experiment in one machine by using "Caliper-min", but I found generating transactions by node takes up 80% of CPU and influences the performance of the system. How do you solve the problem? And can I deploy FabricSharp in a distributed model?

**Comment by RUAN0007** [comment]
Can you separate the caliper-min process into a separate machine, other than the one running FabricSharp? I am in this way.

**Comment by yqcong** [comment]
> Hello, I have reproduced the experiment in one machine by using "Caliper-min", but I found generating transactions by node takes up 80% of CPU and influences the performance of the system. How do you solve the problem? And can I deploy FabricSharp in a distributed model?

Hi ,I also need reproduce the experiment, I am glad to communicate with you!
