### ISSUE TITLE
About Smart Scheduler and DB type

### ISSUE THREAD

**Issue by cezhang52111** [ooibc88/FabricSharp#13]
I am trying to test occ-sharp in FabricSharp. It is said that 'bash environment variable $CC_TYPE for each run of orderer and peer'. I have set the CC_TYPE=occ-sharp and set MV_STORE_PATH to be some path in ~/.bashrc . However, after I start the peer and orderer, deploy the chaincode and send the transaction, the MV_STORE_PATH directory is still emtpy. Does this mean I fail to set the CC_TYPE? I use docker-composer for starting the peer and orderer nodes, which is followed by Fabric's official tutorial. Should I set the CC_TYPE and MV_STORE_PATH  in the docker-composer's yaml file?

Thanks.

**Comment by cezhang52111** [comment]
I tried to set CORE_LEDGER_STATE_STATEDATABASE=UstoreDB in docker-composer-up.yaml. Then, when I tried to run 'peer channel join -b mychannel.block', the peer node crashes and the log shows:
2021-05-21 18:22:37.314 UTC [pvtdatastorage] func1 -> DEBU 0fc Waiting for collection eligibility event

[I d0521 t18:22:37 p00001:416 /usr/local/USTORE/src/utils/env.cc:32] Loaded config:
data_dir: "/ustore_data"
data_file_pattern: "ustore"
access_log_dir: ""
max_segments: 10000
enable_dist_store: false
get_chunk_bypass_worker: true
worker_file: "conf/workers.lst"
recv_threads: 2
http_port: 60600

[I d0521 t18:22:37 p00001:416 /usr/local/USTORE/src/store/lst_store.cc:230] init meta segment
[I d0521 t18:22:37 p00001:416 /usr/local/USTORE/src/store/lst_store.cc:235] init segments done
[I d0521 t18:22:37 p00001:416 /usr/local/USTORE/src/store/lst_store.cc:454] load completed
[I d0521 t18:22:37 p00001:416 /usr/local/USTORE/src/store/lst_store.cc:455]
============= Storage Usage Information ==============
Node Info    |
======================================================
Segment Type |     Maximum |   Allocated |        Used
Count        |       10000 |           0 |           0
======================================================
Chunk Type   |       Count |    Readable |       Bytes
Total        |           0 |       0.00B |           0
Valid        |           0 |       0.00B |           0
Cell         |           0 |       0.00B |           0
Meta         |           0 |       0.00B |           0
Blob         |           0 |       0.00B |           0
Map          |           0 |       0.00B |           0
List         |           0 |       0.00B |           0
Set          |           0 |       0.00B |           0
======================================================
2021-05-21 18:22:37.334 UTC [leveldbhelper] GetIterator -> DEBU 0fd Getting iterator for range [[]byte{0x6d, 0x79, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x31, 0x0}] - [[]byte{0x6d, 0x79, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x31, 0x1}]
2021-05-21 18:22:37.334 UTC [kvledger] newKVLedger -> DEBU 0fe Creating KVLedger ledgerID=mychannel:
SIGILL: illegal instruction
PC=0x7f263eeefebf m=3 sigcode=2

Thanks.

**Comment by Seafoodair** [comment]
how to resolve the question?
