### ISSUE TITLE
question about making peer image

### ISSUE THREAD

**Issue by wwqicode** [ooibc88/FabricSharp#2]
Hello, I'm tring to run fabric#, but I don't know how to make peer image.
I'm using the master branch, and I've got hyperledger/fabric-orderer:forkbase, hyperledger/fabric-ccenv:forkbase and hyperledger/forkbase. I also export DOCKER_DYNAMIC_LINK=true, and tried 'make peer-docker'. But I made image fail, it shows 'cannot find package "ustore" in any of: ...'.
What should I do? What mistakes I have make?
Thank you.

**Comment by Matthewbalala** [comment]
you can checkout  sigmod20
