### ISSUE TITLE
make orderer-docker error

### ISSUE THREAD

**Issue by Seafoodair** [ooibc88/FabricSharp#5]
error message：
orderer/common/blockcutter/scheduler/common/ds.go:7:2: cannot find package "." in:
        /go/src/github.com/hyperledger/fabric/vendor/github.com/emirpasic/gods/lists/arraylist
orderer/common/blockcutter/scheduler/common/ds.go:8:2: no Go files in /go/src/github.com/hyperledger/fabric/vendor/github.com/willf/bloom

**Comment by RUAN0007** [comment]
Try Pull Request #3.

**Comment by Seafoodair** [comment]
Building build/bin/orderer
GOBIN=/go/src/github.com/hyperledger/fabric/build/bin go install -tags "" -ldflags "-X github.com/hyperledger/fabric/common/metadata.Version=2.2.0 -X github.com/hyperledger/fabric/common/metadata.CommitSHA=58a3693 -X github.com/hyperledger/fabric/common/metadata.BaseDockerLabel=org.hyperledger.fabric -X github.com/hyperledger/fabric/common/metadata.DockerNamespace=hyperledger" github.com/hyperledger/fabric/cmd/orderer
orderer/common/blockcutter/scheduler/common/ds.go:7:2: cannot find package "." in:
        /go/src/github.com/hyperledger/fabric/vendor/github.com/emirpasic/gods/lists/arraylist
orderer/common/blockcutter/scheduler/common/ds.go:8:2: no Go files in /go/src/github.com/hyperledger/fabric/vendor/github.com/willf/bloom
make: *** [Makefile:209: build/bin/orderer] Error 1
Removing intermediate container 870b1670bb5f
The command '/bin/sh -c make orderer GO_TAGS=${GO_TAGS}' returned a non-zero code: 2
Makefile:231: recipe for target 'build/images/orderer/.dummy--2.2.0-snapshot-58a3693c6' failed
make: *** [build/images/orderer/.dummy--2.2.0-snapshot-58a3693c6] Error 2

**Comment by Seafoodair** [comment]
Hello, I'm tring to run fabric#, I try to make order-iamge
I'm using the master branch, and I've install hyperledger2.2,make peer success.but I try to make orderer-docker failed,error message 
Building build/bin/orderer
GOBIN=/go/src/github.com/hyperledger/fabric/build/bin go install -tags "" -ldflags "-X github.com/hyperledger/fabric/common/metadata.Version=2.2.0 -X github.com/hyperledger/fabric/common/metadata.CommitSHA=58a3693 -X github.com/hyperledger/fabric/common/metadata.BaseDockerLabel=org.hyperledger.fabric -X github.com/hyperledger/fabric/common/metadata.DockerNamespace=hyperledger" github.com/hyperledger/fabric/cmd/orderer
orderer/common/blockcutter/scheduler/common/ds.go:7:2: cannot find package "." in:
/go/src/github.com/hyperledger/fabric/vendor/github.com/emirpasic/gods/lists/arraylist
orderer/common/blockcutter/scheduler/common/ds.go:8:2: no Go files in /go/src/github.com/hyperledger/fabric/vendor/github.com/willf/bloom
make: *** [Makefile:209: build/bin/orderer] Error 1
Removing intermediate container 870b1670bb5f
The command '/bin/sh -c make orderer GO_TAGS=${GO_TAGS}' returned a non-zero code: 2
Makefile:231: recipe for target 'build/images/orderer/.dummy--2.2.0-snapshot-58a3693c6' failed
make: *** [build/images/orderer/.dummy--2.2.0-snapshot-58a3693c6] Error 2
What should I do? What mistakes I have make?
Thank you.

**Comment by RUAN0007** [comment]
Have you pour into relevant dependencies file in /go/src/github.com/hyperledger/fabric/vendor/github.com/willf/bloom and go/src/github.com/hyperledger/fabric/vendor/github.com/emirpasic? Pull Request 3 have done so.

**Comment by Seafoodair** [comment]
> 您是否已在/go/src/github.com/hyperledger/fabric/vendor/github.com/willf/bloom和go / src / github.com / hyperledger / fabric / vendor / github.com / emirpasic中注入相关的依赖项文件？拉取请求3已这样做。

thank you，I solve part of question.but I can not find emirpasic link.Can pull the emippasic github address？

**Comment by RUAN0007** [comment]
Here your go https://github.com/emirpasic/gods. If everything ok, pls close this issue.

**Comment by Seafoodair** [comment]
> Here your go https://github.com/emirpasic/gods. If everything ok, pls close this issue.

thank you

**Comment by cezhang52111** [comment]
I also encounter the same error:
orderer/common/blockcutter/scheduler/common/ds.go:7:2: cannot find package "." in:
        /go/src/github.com/hyperledger/fabric/vendor/github.com/emirpasic/gods/lists/arraylist
orderer/common/blockcutter/scheduler/common/ds.go:8:2: no Go files in /go/src/github.com/hyperledger/fabric/vendor/github.com/willf/bloom
make: *** [Makefile:209: build/bin/orderer] Error 1

By the way, I do not have the directory /go/src/github.com/hyperledger/fabric/ and all sub-directories. Should this directory be created during the installation of the standard Fabric 2.2? I only have this directory: go/src/github.com/hyperledger/fabric-samples. Thanks.

**Comment by LErickMX** [comment]
> > 您是否已在/go/src/github.com/hyperledger/fabric/vendor/github.com/willf/bloom和go / src / github.com / hyperledger / fabric / vendor / github.com / emirpasic中注入相关的依赖项文件？拉取请求3已这样做。
> 
> thank you，I solve part of question.but I can not find emirpasic link.Can pull the emippasic github address？

请问一下你这个问题是怎么解决的，我也遇到了这个问题
