### ISSUE TITLE
About experiments

### ISSUE THREAD

**Issue by Sybilzz** [ooibc88/FabricSharp#6]
I'm a student doing research on the performance of Consortium Blockchain and want to test their performance. I want to learn from your experiment based on the benchmark of Smallbank or YCSB, can you provide some message to me? How should I t invoke the chaincode and control the transaction arrival rate? Can I use some commands to do these, or do I need to design my own program？Thank you.

**Comment by RUAN0007** [comment]
Hi, you can use Caliper (https://github.com/hyperledger/caliper) for the benchmark. You can definitely build your own benchmarking script.

**Comment by Sybilzz** [comment]
thanks
