### ISSUE TITLE
About experiment

### ISSUE THREAD

**Issue by Sybilzz** [ooibc88/FabricSharp#8]
Hi, If it's convenient, could you share the script of YCSB in Caliper with me？

**Comment by RUAN0007** [comment]
Our Caliper is heavily optimized for our own usage and tightly coupled to our environment. 
As it may contain confidential information, pls understand that we are not convenient to disclose it.

**Comment by RUAN0007** [comment]
Hi, we take some efforts to strip away the platform-specific artifacts from our own Caliper. 
We have released it in https://github.com/RUAN0007/caliper-min. 
You can refer to YCSB, Smallbank, and another Custom workloads under benchmark/ directory of the above repo.

**Comment by Sybilzz** [comment]
Thank you very much, it will help me a lot.
